# config.yaml

context_builder_params:
  use_community_summary: false
  shuffle_data: true
  include_community_rank: true
  min_community_rank: 0
  community_rank_name: "rank"
  include_community_weight: true
  community_weight_name: "occurrence weight"
  normalize_community_weight: true
  max_tokens: 12000
  context_name: "Reports"

map_llm_params:
  max_tokens: 1000
  temperature: 0.0
  response_format:
    type: "json_object"

reduce_llm_params:
  max_tokens: 2000
  temperature: 0.0